### ISSUE TITLE
Please use Faker

### ISSUE THREAD

**Issue by dgrammatiko** [alexandreelise/file_contentcli#2]
Hey, @alexandreelise nice work. Can you please include the popular Faker library: https://github.com/FakerPHP/Faker ?

The reason is simple: the content will be random and closer to what real content might be in a real-world scenario.

Thanks

**Comment by alexandreelise** [comment]
Hi @dgrammatiko thanks for your kind words. I wanted to use faker in the first place. But after thought I would be a nice to have but unecessary dependency regarding the goal I had when using this simple script. But I don't totally reject the idea and I might add faker in a future version in another branch. Thanks for your feedback.

**Comment by alexandreelise** [comment]
Hi @dgrammatiko I added faker and also added the same sample feature for users using faker. I did it in a joomla package. If you are still interested. I can send it to you via email or Google Drive. Take care.
